version: "3.8"
name: app

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get({host:'localhost',port:process.env.PORT||5000},()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: http://backend:5000
        BASE_URL: http://backend:5000
    env_file:
      - ./frontend/.env
    environment:
      - BASE_URL=http://backend:5000
      - NEXT_PUBLIC_BASE_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
