version: "3.8"
name: app

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5001
    ports:
      - "5001:5000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get({host:'localhost',port:process.env.PORT||5000},()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: http://backend:5001
        BASE_URL: http://backend:5001
    environment:
      - BASE_URL=http://backend:5001
      - NEXT_PUBLIC_BASE_URL=http://backend:5001
    ports:
      - "3001:3000"
    depends_on:
      backend:
        condition: service_healthy
