name: first
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - BASE_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - PORT=5000
    ports:
      - 5000:5000
