services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BASE_URL: http://backend:4000 # ✅ internal network hostname
        BASE_URL: http://backend:4000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://backend:4000 # ✅ not localhost
      - BASE_URL=http://backend:4000
    depends_on:
      - backend
